spring:
  flyway:
    baselineOnMigrate: ${BASELINE_ON_MIGRATE:true}
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

server:
  port : 8181

gladiators:
  hoplomachus:
    health: 100
    armour: 50
    attack: 10
    speed: 8
    luck: 7
  retiarius:
    health: 100
    armour: 50
    attack: 10
    speed: 8
    luck: 7